; Generated by npm run release:sync; edit core/release/release-config.json.
#define MyAppName "Clash for Windows"
#define MyAppVersion "0.20.39.4"
#define MyAppDisplayVersion "Opt-4"
#define MyAppPublisher "Clash for Windows"
#define MyAppURL "https://github.com/Z-Siqi/Clash-for-Windows_Chinese"
#define MyAppExeName "Clash for Windows.exe"
#define MyAppAssocName "Clash.for.Windows.Setup_Opt-4"
